apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: system
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: serviceaccount-quota
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https